fn create context oci-context --provider oracle
fn update context oci-context oracle.region us-ashburn-1
fn update context oci-context oracle.compartment-id <COMPARTMENT_OCID>
fn use context oci-context

[opc@oci-admin-01 ~]$ fn update context oci-context oracle.region us-ashburn-1

Fn: open /home/opc/.fn/contexts/.yaml: no such file or directory

See 'fn <command> --help' for more information. Client version: 0.6.43
[opc@oci-admin-01 ~]$

fn update context oci-context api-url https://functions.us-ashburn-1.oci.oraclecloud.com

fn create context oci-context --provider oracle \
  --api-url https://functions.us-ashburn-1.oci.oraclecloud.com

fn create context oci-context \
  --provider oracle \
  --api-url https://functions.us-ashburn-1.oci.oraclecloud.com \
  --oracle.region us-ashburn-1 \
  --oracle.compartment-id ocid1.compartment.oc1..aaaaaaaal3ny7cdvz3ovgcq43x7vqexyyy4s2fozfo4zhked7xsyzbhsx7bq

Option 2 â€” Create + Edit YAML
bash
Kopieren
Bearbeiten
fn create context oci-context \
  --provider oracle \
  --api-url https://functions.us-ashburn-1.oci.oraclecloud.com

nano ~/.fn/contexts/oci-context.yaml
Then manually add:

yaml
Kopieren
Bearbeiten
oracle.region: us-ashburn-1
oracle.compartment-id: <COMPARTMENT_OCID>

fn config function cloud-guard-processing-app cloud_guard_processor BUCKET_NAME cloud-guard-findings-bucket

Successfully created function: cloud_guard_processor with iad.ocir.io/acscloudengineering/cloud-guard-functions/cloud_guard_processor:0.0.4
[opc@oci-admin-01 cloud_guard_processor]$ fn invoke cloud-guard-processing-app cloud_guard_processor
Error invoking function. status: 502 message: function failed

oci logging search-logs \
  --search-query "search \"FunctionsExecution\" where appName = 'cloud-guard-processing-app'" \
  --time-start 10m


echo "_L>Dr8F-m8_]YrN>TaF8" | docker login iad.ocir.io  \
--username "acscloudengineering/gregory.ohwerhi@oracle.com" \
--password-stdin

tZ[-RP#I#TOieRz79SmC

echo "tZ[-RP#I#TOieRz79SmC" | docker login iad.ocir.io  \
--username "acscloudengineering/gregory.ohwerhi@oracle.com" \
--password-stdin

echo "tZ[-RP#I#TOieRz79SmC" | docker login iad.ocir.io  --username "acscloudengineering/oracleidentitycloudservice/gregory.ohwerhi@oracle.com" --password-stdin

[opc@oci-admin-01 cloud_guard_processor]$ echo '{"finding":"test"}' | fn invoke cloud-guard-processing-app cloud_guard_processor
Error: {'target_service': 'object_storage', 'status': 404, 'code': 'BucketNotFound', 'opc-request-id': 'iad-1:2Kats6lJBJf6Wj0gTxrwpo-dXoP0epgmfsbFx-xilfZaUskGPuks689lbQudxNs8', 'message': "Either the bucket named 'cloud-guard-findings-bucket' does not exist in the namespace 'acscloudengineering' or you are not authorized to access it", 'operation_name': 'put_object', 'timestamp': '2025-08-18T09:15:41.614311+00:00', 'client_version': 'Oracle-PythonSDK/2.158.0', 'request_endpoint': 'PUT https://objectstorage.us-ashburn-1.oraclecloud.com/n/acscloudengineering/b/cloud-guard-findings-bucket/o/2025-08-18T09-15-41Z_unknown_finding.json', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_bucketnotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/PutObject for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message."}



[opc@oci-admin-01 cloud_guard_processor]$ fn list functions cloud-guard-processing-app
NAME                    IMAGE                                                                                   ID
cloud_guard_processor   iad.ocir.io/acscloudengineering/cloud-guard-functions/cloud_guard_processor:0.0.8       ocid1.fnfunc.oc1.iad.aaaaaaaaanek6owb3wzp6yiljtyp3fnmtgj6ywghigm524hpxb6s3fyjqvhq
[opc@oci-admin-01 cloud_guard_processor]$
